"""Add new table for blogs

Revision ID: d39fe31421d2
Revises: 603993a3b0c9
Create Date: 2019-11-29 18:58:38.316590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39fe31421d2'
down_revision = '603993a3b0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'user')
    # ### end Alembic commands ###
